sudo: required

env:
  global:
    - MINECRAFT_SERVER_MAJOR_VERSION=1.16
    - MINECRAFT_SERVER_VERSION=1.16.1

language: generic

services:
  - docker

script:
  - docker build -t gregoireweber/minecraft-server:latest .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      docker tag gregoireweber/minecraft-server:latest gregoireweber/minecraft-server:"$MINECRAFT_SERVER_MAJOR_VERSION";
      docker tag gregoireweber/minecraft-server:latest gregoireweber/minecraft-server:"$MINECRAFT_SERVER_VERSION";
      docker tag gregoireweber/minecraft-server:latest gregoireweber/minecraft-server:"$MINECRAFT_SERVER_VERSION"-"$TRAVIS_BUILD_NUMBER";
      docker push gregoireweber/minecraft-server:latest;
      docker push gregoireweber/minecraft-server:"$MINECRAFT_SERVER_MAJOR_VERSION";
      docker push gregoireweber/minecraft-server:"$MINECRAFT_SERVER_VERSION";
      docker push gregoireweber/minecraft-server:"$MINECRAFT_SERVER_VERSION"-"$TRAVIS_BUILD_NUMBER";
    fi